my.rabbitmq.container.name: stockSim_rabbitmq
my.serverregistry.container.name: stockSimServerRegistry
my.serverregistry.container.port: 8100


spring:
  application:
    name: stockSim-Email
  mail:
    host: YOUR-EMAIL-SMTP
    port: 587
    username: YOUR-EMAIL
    password: YOUR-EMAIL-PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${my.rabbitmq.container.name}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
      direct:
        prefetch: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      expose: "*"

server:
  port: 80

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${my.serverregistry.container.name}:${my.serverregistry.container.port}/eureka/
