server:
  port: 80

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:80/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: eureka-server