server:
  port: 8100

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: eureka-server